

publish-to-beta:
  image: nginx
  tags:
    - infy-aws-docker-windows
  stage: release
  only:
    - branches
    - /^release-.*$/
  except:
    - master
  when: manual
  script:
    - ./gradlew publish -PpublishBetaArtifactsFromTaskBranch=true --info
